### ISSUE TITLE
URLs do not work (Error 404)

### ISSUE THREAD

**Issue by gytis** [fabric8-launch/appdev-documentation#776] opened 2017-11-06 13:28 UTC
"Using OpenShift to Create a Booster" link in a [2.5.2. Why Circuit Breaker is Important](https://doc-stage.usersys.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/spring_boot_tomcat_runtime_guide/#why_circuit_breaker_is_important) section's note leads to an not existing page.

**Comment by gytis** [comment] 2017-11-06 18:02
"Install and Configure a Single-node OpenShift Cluster" link also point to a not existing resource. See section 2.5.4.1.

**Comment by gytis** [comment] 2017-11-06 20:12
In [2.5.9. Circuit Breaker Resources](https://doc-stage.usersys.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/spring_boot_tomcat_runtime_guide/#circuit_breaker_resources) links to Swarm and Vert.x boosters are pointing to the not existing resources.

**Comment by tradej** [comment] 2017-11-07 09:40
This issue is caused by the fact that the staging documentation links to yet unpublished documents. That is true for all links to RHOAR books. The links will work once published.

**Please, do not report any further broken links unless they point outside of the RHOAR documentation, or they're references within one book.**

**Comment by gytis** [comment] 2017-11-07 09:41
OK, didn't know that.

**Comment by tradej** [comment] 2017-11-07 09:58
It's all right, we only discovered it thanks to this issue, so credit where it's due. :)

**Comment by rhoads-zach** [comment] 2017-11-08 17:26
closing this issue

**Closed by rhoads-zach** 2017-11-08 17:26 UTC
Labels: Type | Bug
