### ISSUE TITLE
Secured HTTP Mission / Spring Boot: wrong service/route name in 2.6.7. Interacting with the Secured Booster

### ISSUE THREAD

**Issue by metacosm** [fabric8-launch/appdev-documentation#849] opened 2017-11-09 11:20 UTC
The name of the service must match the name that is defined by the Launcher-generated POM. This issue is probably common across all runtimes. In the Spring Boot case, the artifact id is: `booster-rest-http-secured-spring-boot`

**Comment by metacosm** [comment] 2017-11-09 11:20
See #848

**Comment by tradej** [comment] 2017-11-10 11:23
Closing as a duplicate of #848 and expanding the scope thereof.

**Closed by tradej** 2017-11-10 11:23 UTC
